cats_dogs_128:
  dataset: Dogs vs Cats
  description: TODO

  general:
    image_size: 128
    label_mapping:
      Cat: 0
      Dog: 1
      Unknown: 'x'

    name_class_delimiter: _  # images will be saved in format <name>_<class_number>

  paths:
    imgs: ./data/PetImages
    save: ./server/static/images

  loader:
    shuffle: True
    label_format: one-hot

  preprocessing:
    grayscale: False
    rescale_with_crop: True
    normalization: False
    centering: False
    standarization: False
    strict_balance: False

  preprocessing_npy:
    grayscale: False
    rescale_with_crop: True
    normalization: True
    centering: True
    standarization: True
    strict_balance: False

# !TODO create config to save both png and npy
# !TODO add numpy save
# !TODO add npy filename
testset:
  dataset: Dogs vs Cats
  description: TODO

  general:
    image_size: 128
    label_mapping:
      Unknown: 255

    name_class_delimiter: _  # images will be saved in format <name>_<class_number>

  paths:
    imgs: ./data/TestImages
    save: ./server/static/images

  loader:
    shuffle: False
    label_format: one-hot

  preprocessing:
    grayscale: False
    rescale_with_crop: True
    normalization: False
    centering: False
    standarization: False
    strict_balance: False

  preprocessing_npy:
    grayscale: False
    rescale_with_crop: True
    normalization: True
    centering: True
    standarization: True
    strict_balance: False
